#!/usr/bin/env python
from __future__ import division
import sys
import cv2
import numpy as np
from apriltag_tracker._AprilTagTracker import AprilTagTracker

datatype = np.float32

img = cv2.imread('../data/test_tag_0.png')
img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

tracker = AprilTagTracker('../config/params.yaml')

theta = np.eye(4).astype(datatype)

tracker.track(img, theta)

print 'Obtained theta is {0}'.format(theta)